

insert into user_account (user_id, user_password, authority, email, nickname, memo ,created_at, updated_at)
values('ggamangso', 'test1234', 'user','test@mail.com', 'ggamang', null, now(), now());

insert into chat(chat_id, user_id, created_at, updated_at)
values(1, 'ggamangso', now(),now());

insert into message (id, chat_id, role, content, corrected_content, is_bookmarked, message_memo, created_at, updated_at)
values (1, 1, 'lobortis', 'ltomaini0@tmall.com', null, true, 'Duis at velit eu est congue elementum.',now(), now()),
       (2, 1, 'venenatis', 'lpharrow1@gnu.org', 'Male', true, 'In eleifend quam a odio.',now(), now()),
       (3, 1, 'at', 'nburnyeat2@ustream.tv', 'Polygender', true, 'Nullam varius.',now(), now()),
       (4, 1, 'rhoncus', 'hscruton3@newyorker.com', null, true, 'Nunc purus.',now(), now()),
       (5, 1, 'eros', 'hwattingham4@yolasite.com', 'Male', false, 'Phasellus sit amet erat.',now(), now()),
       (6, 1, 'felis', 'cflippini5@delicious.com', 'Female', false, 'Aliquam erat volutpat.',now(), now()),
       (7, 1, 'magna', 'rpottes6@globo.com', null, false, null,now(), now()),
       (8, 1, 'libero', 'gdelayglesia7@webnode.com', null, true, 'Phasellus in felis.',now(), now()),
       (9, 1 , 'eu', 'jwyeth8@trellian.com', null, false, 'Vestibulum rutrum rutrum neque.',now(), now()),
       (10, 1, 'in', 'pkeelinge9@mashable.com', null, true, 'Morbi vel lectus in quam fringilla rhoncus.',now(), now()),
       (11, 1, 'sagittis', 'ewarena@wiley.com', 'Male', true, 'Phasellus in felis.',now(), now()),
       (12, 1, 'eget', 'mantoniazzib@hibu.com', 'Male', true, null,now(), now()),
       (13, 1, 'pharetra', 'cstowc@over-blog.com', null, true, 'Mauris sit amet eros.',now(), now()),
       (14, 1, 'morbi', 'asheasbyd@sakura.ne.jp', null, false, 'Nam tristique tortor eu pede.',now(), now()),
       (15, 1, 'consequat', 'cjahne@illinois.edu', 'Female', false, 'Suspendisse ornare consequat lectus.',now(), now()),
       (16, 1, 'amet', 'fdymentf@lulu.com', 'Male', true, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',now(), now()),
       (17, 1, 'sed', 'dcrannageg@mac.com', 'Female', false, 'Praesent blandit.',now(), now()),
       (18, 1, 'volutpat', 'ksimonsenh@qq.com', 'Male', false, 'Donec posuere metus vitae ipsum.',now(), now()),
       (19, 1, 'at', 'hpellingtoni@home.pl', 'Polygender', false, 'Maecenas tincidunt lacus at velit.',now(), now()),
       (20, 1, 'tellus', 'lecobj@cargocollective.com', 'Female', true, 'Pellentesque eget nunc.',now(), now()),
       (21, 1, 'tristique', 'cgethenk@imageshack.us', 'Male', true, null,now(), now()),
       (22, 1, 'arcu', 'hjillsl@acquirethisname.com', 'Male', false,'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.',now(), now()),
       (23, 1, 'pede', 'ditzhayekm@aol.com', null, true,'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.',now(), now()),
       (24, 1, 'luctus', 'zbullinghamn@cnbc.com', 'Male', true, 'Praesent blandit.',now(), now()),
       (25, 1, 'volutpat', 'kiveo@omniture.com', 'Female', true, 'Phasellus sit amet erat.',now(), now()),
       (26, 1, 'lacinia', 'dshillingfordp@loc.gov', 'Male', false, null,now(), now()),
       (27, 1, 'vestibulum', 'iskedgellq@princeton.edu', null, true, 'Aenean auctor gravida sem.',now(), now()),
       (28, 1, 'viverra', 'abraddenr@who.int', null, true, 'Curabitur in libero ut massa volutpat convallis.',now(), now()),
       (29, 1, 'at', 'bbooleys@narod.ru', null, true,'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',now(), now()),
       (30, 1, 'mi', 'cgalletleyt@yolasite.com', 'Non-binary', false, 'In sagittis dui vel nisl.',now(), now()),
       (31, 1, 'praesent', 'cbursnellu@rediff.com', 'Female', true, 'Suspendisse accumsan tortor quis turpis.',now(), now()),
       (32, 1, 'semper', 'jcarthyv@bigcartel.com', 'Male', false, 'Duis aliquam convallis nunc.',now(), now()),
       (33, 1, 'id', 'mcogglesw@geocities.com', null, true, 'Vivamus in felis eu sapien cursus vestibulum.',now(), now()),
       (34, 1, 'rutrum', 'temsleyx@xinhuanet.com', 'Male', false, null,now(), now()),
       (35, 1, 'sapien', 'rmacdougaly@washington.edu', null, true, null,now(), now()),
       (36, 1, 'porttitor', 'arodenburgz@go.com', 'Female', true, null,now(), now()),
       (37, 1, 'bibendum', 'idarnbrook10@ow.ly', 'Female', true, 'Morbi vel lectus in quam fringilla rhoncus.',now(), now()),
       (38, 1, 'habitasse', 'gloughney11@utexas.edu', 'Female', true, 'Proin at turpis a pede posuere nonummy.',now(), now()),
       (39, 1, 'semper', 'jeathorne12@dropbox.com', 'Male', false, 'Nulla tellus.',now(), now()),
       (40, 1, 'pellentesque', 'fasplin13@blogtalkradio.com', 'Male', true, null,now(), now()),
       (41, 1, 'sit', 'kvenny14@cocolog-nifty.com', 'Female', true, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',now(), now()),
       (42, 1, 'orci', 'olamond15@dion.ne.jp', null, false, null,now(), now()),
       (43, 1, 'justo', 'fdubois16@nature.com', 'Male', false, 'Nam dui.',now(), now()),
       (44, 1, 'convallis', 'tglyne17@amazon.co.jp', 'Male', true, null,now(), now()),
       (45, 1, 'odio', 'kbunning18@earthlink.net', 'Female', false, 'In eleifend quam a odio.',now(), now()),
       (46, 1, 'magna', 'mmariel19@slashdot.org', 'Male', false, 'Maecenas pulvinar lobortis est.',now(), now()),
       (47, 1, 'non', 'nschuster1a@imageshack.us', 'Male', false, null,now(), now()),
       (48, 1, 'nullam', 'creavell1b@xrea.com', null, true,  'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',now(), now()),
       (49, 1, 'in', 'nbotcherby1c@twitter.com', 'Male', true, 'Praesent id massa id nisl venenatis lacinia.',now(), now()),
       (50, 1, 'justo', 'rmacnaughton1d@msn.com', null, false, 'Nam dui.',now(), now()),
       (51, 1, 'sit', 'bheams1e@stumbleupon.com', 'Genderfluid', true, 'Mauris ullamcorper purus sit amet nulla.',now(), now()),
       (52, 1, 'penatibus', 'avampouille1f@marketwatch.com', null, false, 'Duis bibendum.',now(), now()),
       (53, 1, 'velit', 'mharbron1g@howstuffworks.com', 'Male', true, 'Pellentesque viverra pede ac diam.',now(), now()),
       (54, 1, 'odio', 'mmcpharlain1h@ycombinator.com', null, true, null,now(), now()),
       (55, 1, 'eleifend', 'msheather1i@house.gov', 'Male', true, 'Proin risus.',now(), now()),
       (56, 1, 'ante', 'mmacghee1j@goo.ne.jp', 'Male', true, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.',now(), now()),
       (57, 1, 'turpis', 'ltort1k@canalblog.com', null, true, null,now(), now()),
       (58, 1, 'ac', 'ncastanos1l@loc.gov', 'Male', true, 'Praesent id massa id nisl venenatis lacinia.',now(), now()),
       (59, 1, 'dapibus', 'averdie1m@w3.org', 'Male', false, 'Cras pellentesque volutpat dui.',now(), now()),
       (60, 1, 'sapien', 'dreeson1n@nyu.edu', 'Female', true, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.',now(), now()),
       (61, 1, 'integer', 'asowden1o@fc2.com', 'Female', true, 'Aliquam erat volutpat.',now(), now()),
       (62, 1, 'a', 'asorrell1p@google.es', 'Female', false, 'Suspendisse ornare consequat lectus.',now(), now()),
       (63, 1, 'montes', 'eboyland1q@cargocollective.com', 'Non-binary', false, null,now(), now()),
       (64, 1, 'rhoncus', 'ohegge1r@china.com.cn', 'Female', true, 'In hac habitasse platea dictumst.',now(), now()),
       (65, 1, 'amet', 'mprobbings1s@furl.net', 'Female', false, 'Morbi porttitor lorem id ligula.',now(), now()),
       (66, 1, 'ultrices', 'egalletly1t@creativecommons.org', 'Male', false,'Duis consequat dui nec nisi volutpat eleifend.',now(), now()),
       (67, 1, 'nulla', 'mbraferton1u@lulu.com', null, true, 'Proin eu mi.',now(), now()),
       (68, 1, 'ut', 'gtilburn1v@tripod.com', 'Female', true, 'Suspendisse potenti.',now(), now()),
       (69, 1, 'ante', 'apund1w@umn.edu', null, false, 'Nam dui.',now(), now()),
       (70, 1, 'tristique', 'obesset1x@netvibes.com', null, true, 'Vivamus tortor.',now(), now()),
       (71, 1, 'risus', 'fboak1y@irs.gov', 'Male', false, null,now(), now()),
       (72, 1, 'consequat', 'ashone1z@npr.org', 'Female', true, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.',now(), now()),
       (73, 1, 'congue', 'dpennock20@mit.edu', 'Male', true, 'Duis consequat dui nec nisi volutpat eleifend.',now(), now()),
       (74, 1, 'ligula', 'njagiello21@discuz.net', 'Male', true, 'Donec quis orci eget orci vehicula condimentum.',now(), now()),
       (75, 1, 'a', 'scahalan22@fema.gov', 'Male', false, null,now(), now()),
       (76, 1, 'sem', 'fcrampin23@wordpress.com', null, true, 'Morbi porttitor lorem id ligula.',now(), now()),
       (77, 1, 'ultrices', 'dkember24@buzzfeed.com', 'Genderfluid', false, 'Sed sagittis.',now(), now()),
       (78, 1, 'enim', 'dgiffard25@xrea.com', 'Female', true, 'Praesent lectus.',now(), now()),
       (79, 1, 'elementum', 'flangan26@zimbio.com', 'Genderqueer', false, null,now(), now()),
       (80, 1, 'eleifend', 'smacskeaghan27@etsy.com', null, true, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.',now(), now()),
       (81, 1, 'urna', 'pdyte28@furl.net', 'Male', true, 'Mauris sit amet eros.',now(), now()),
       (82,1, 'tortor', 'gdinehart29@scribd.com', null, false, 'Aliquam sit amet diam in magna bibendum imperdiet.',now(), now()),
       (83, 1, 'nisi', 'bswatradge2a@paginegialle.it', 'Female', false, 'Praesent id massa id nisl venenatis lacinia.',now(), now()),
       (84, 1, 'vel', 'mfolke2b@odnoklassniki.ru', 'Male', false, 'Ut tellus.',now(), now()),
       (85, 1, 'eu', 'sboyen2c@artisteer.com', 'Male', true, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.',now(), now()),
       (86, 1, 'vitae', 'ztarte2d@ox.ac.uk', null, true, 'Pellentesque ultrices mattis odio.',now(), now()),
       (87, 1, 'consectetuer', 'smewton2e@independent.co.uk', null, true, 'Pellentesque at nulla.',now(), now()),
       (88, 1, 'id', 'alearman2f@cdbaby.com', null, true, 'Integer tincidunt ante vel ipsum.',now(), now()),
       (89, 1, 'integer', 'wmullen2g@rambler.ru', 'Male', true, 'Integer ac neque.',now(), now()),
       (90, 1, 'erat', 'nannable2h@xing.com', null, false,'In est risus, auctor sed, tristique in, tempus sit amet, sem.',now(), now()),
       (91, 1, 'odio', 'sbarfield2i@is.gd', 'Male', true, 'In hac habitasse platea dictumst.',now(), now()),
       (92, 1, 'laoreet', 'icouthard2j@ehow.com', null, true, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.',now(), now()),
       (93, 1, 'sagittis', 'trowlson2k@mac.com', 'Female', true, null,now(), now()),
       (94, 1, 'consequat', 'moldnall2l@163.com', null, false, 'Donec quis orci eget orci vehicula condimentum.',now(), now()),
       (95, 1, 'ornare', 'fmustchin2m@sakura.ne.jp', 'Female', false, 'Sed sagittis.',now(), now()),
       (96, 1, 'dapibus', 'wocorren2n@sciencedaily.com', 'Female', false, null,now(), now()),
       (97, 1, 'proin', 'cfreda2o@paginegialle.it', 'Female', true, null,now(), now()),
       (98, 1, 'sapien', 'lvannacci2p@ucoz.ru', 'Female', false, 'Nulla tempus.',now(), now()),
       (99, 1, 'quam', 'civantyev2q@last.fm', 'Male', true, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',now(), now()),
       (100, 1, 'magna', 'odyson2r@tuttocitta.it', 'Male', false, 'Integer ac neque.',now(), now());